# Generated by Django 4.1.7 on 2023-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_tag_user_role_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
