# Generated by Django 4.1.7 on 2023-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_task_author_alter_task_executor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(to="main.tag"),
        ),
    ]
